{{- if .Values.roadwarriors.nodeHostnames }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: roadwarriors
  namespace: {{ include "slipmesh.namespace" . }}
  labels:
    {{- include "slipmesh.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: roadwarriors
  template:
    metadata:
      labels:
        app: roadwarriors
        {{- include "slipmesh.labels" . | nindent 8 }}
    spec:
      serviceAccountName: roadwarriors
      hostNetwork: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      {{- toYaml .Values.roadwarriors.nodeHostnames | nindent 22 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: roadwarriors
          image: {{ .Values.image.roadwarriors }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["NET_ADMIN"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RUST_LOG
              value: {{ .Values.logLevel.roadwarriors | quote }}
          resources:
            {{- toYaml .Values.resources.roadwarriors | nindent 12 }}
{{- end }}
